### ISSUE TITLE
using manual game path doesn't work

### ISSUE THREAD

**Issue by viandoxdev** [orchidalloy/PolyConverter#1]
when using manual game path, the gamepath variable is set this way

```c#
// Program.cs line 25
gamePath = $"{File.ReadAllText(ManualGamePath).Trim()}\\Poly Bridge 2_Data\\Managed";
```

addind the path to the Managed folder to it, but when loading the games libraries this path is added again

```c#
// Program.cs line 72
PolyBridge2Assembly = Assembly.LoadFrom($"{gamePath}\\Poly Bridge 2_Data\\Managed\\Assembly-CSharp.dll");
```

causing an error because it ends up searching for the libraries in "${gamepath}\Poly Bridge 2_Data\Managed\Poly Bridge 2_Data\Managed\library.dll"

![Sans titre](https://user-images.githubusercontent.com/43315863/89101296-f68fe200-d3fe-11ea-8531-e2d7bd969f0c.png)

**Comment by hollowstrawberry** [comment]
Oh damn, thank you
